language: node_js
node_js:
- 10.12.0
cache:
  directories:
  - node_modules
install:
- npm install
- npm rebuild --runtime=electron --target=2.0.10 --disturl=https://atom.io/download/electron
script:
- npm run lint
- npm test
- npm run build
after_script:
- git config --global user.email "builds@travis-ci.com"
- git config --global user.name "Travis CI"
- git config --global push.default simple
- mkdir reports
- git checkout $TRAVIS_BRANCH
- git pull
- (npm run lint) > ./reports/$TRAVIS_BUILD_NUMBER-report.txt
- CI=true npm test >> ./reports/$TRAVIS_BUILD_NUMBER-report.txt 2>&1
- (npm run build) >> ./reports/$TRAVIS_BUILD_NUMBER-report.txt
- git add .
- git commit --no-verify -m "[skip travis] Reports for Build $TRAVIS_BUILD_NUMBER uploaded."
- git remote add repo https://${GH_TOKEN}:x-oauth-basic@github.com/juanam/WYA.git
- git push repo $TRAVIS_BRANCH
env:
  global:
    secure: Zf2OHCtQtDaOhPkGiSH3ObMj99MrZrtdG7yfaPiCFtIpV4ySJY2YPIpDOdl428W1Fe4Eflo/2966HuMMh5Bw2+RZjSXfSehjj8C4bZtaiJ1NeS4JXq8UsFZ0CzHm5gY9pBZx2F4Mofd3SDoslvTtpspeVBfmB9VvCurIukaGa71owh/XX/1ag2mn/0KoI5g+tgmOsj207nxH6bjkja9pO+kjeMhT6YAfeCi0H8fr8vm6fILho4i70/PLJjIuIcXkE+fefnj2rFxgDg2xAbRI5aHTL0VipdLtxX6qmea81zyzB2/9rX32soVruDiDkrdNA1wH0NcCXgfsg5CSQjCNov3Q76R59sYG1QZ9lYxbOxZv4HM5sytZrPoJ3DuihQDU+MFq0oHioZN71vllS2uQd3cWPP/cAZaZ1JW6HMrz+DZO71oAyj6rER/4QSHCITkBRcJ1wulXI0BIw93ZNy5LS1Q0YXxccGC4XEM/vLZzOcIgSzXsygkuHJjgZmCZ+RroaWGO8SfXkovvp87NjLPJnMJ9PwVSp/cHqokBRK9S25hn7KOz6KIQoJcBjzL8wU0gjxZDpkJTd+EbK6wgmH6QrFzyDwVW5Tj6B9/xGl9+K7BbITZPCO9hXNVlZgqeFx+dYJdFVcZGhVQEKoV8d0hSyfDRHLoMcAYZc0pft29Qr3o=
